### /Get

GET http://localhost:5003

### registr user to post auth register
POST http://localhost:5003/auth/register

Content-Type: application/json
{
    "username": "random@gmail.com",
    "password": "12345"
}

### login user to auth login
POST http://localhost:5003/auth/login

Content-Type: application/json
{
    "username": "random@gmail.com",
    "password": "12345"
}

### Fetch all todos GET /TODOS (protected)
GET http://localhost:5003/todos 
Authorization: token goes here


### creates a new todo
POST http://localhost:5003/todos
Authorization: token goes here

Content-Type: applicaiton/application/json

{
    "task": "Finish coding the projects"
}


###update a todo
PUT http://localhost:5003/todos/2

Authorization: 
Content-Type: application/json

{
    "completed": 1
}